SENDER_EMAIL = "" # Sender's Email Address
SENDER_PASSWORD = ""  # Your 16-character Google (Gmail) App Password (no spaces needed)
# For example: aaaabbbbccccdddd

NOTIFICATION_TO = "" # Receiver's Email Address

# NOTIFICATION_CC = ""  # Add Email Address , if sending email to other users  