SENDER_EMAIL = "vrize.test1407@gmail.com"
SENDER_PASSWORD = "pozsvfkvklozeaai"  # Your 16-character Google (Gmail) App Password (no spaces needed)
NOTIFICATION_TO = "ishaan.ranjan16@gmail.com"

# NOTIFICATION_CC = ""